version: '3.4'

services:
  sqlserver:
    volumes:
      - ./.containers/${ENVIRONMENT}/mssql:/var/opt/mssql/data
  rabbitmq:
    volumes:
      - ./.containers/${ENVIRONMENT}/rabbitmq/data:/var/lib/rabbitmq
      - ./.containers/${ENVIRONMENT}/rabbitmq/logs:/var/log/rabbitmq
  seq:
    volumes:
      - ./.containers/${ENVIRONMENT}/seq/logs:/data